
#================
#=== Automations
#================
automation:

  #======================================
  #=== SET UI DEFAULTS WHERE APPROPRIATE
  #======================================
  #=========
  #=== Font
  #=========
  - alias: Irrigation UI Set Default Font
    trigger:
      - platform: homeassistant
        event: start

      - platform: state
        entity_id: input_text.irrigation_ui_font_family
        to: ''

    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_text.irrigation_ui_font_family
          state: 'unknown'

        - condition: state
          entity_id: input_text.irrigation_ui_font_family
          state: ''

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_ui_font_family
          value: var(--primary-font-family)


  #================
  #=== User Name 1
  #================
  - alias: Irrigation UI Set User Name 1
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.notifications_user1_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.notifications_user1_name
          value: User 1


  #================
  #=== User Name 2
  #================
  - alias: Irrigation UI Set User Name 2
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.notifications_user2_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.notifications_user2_name
          value: User 2


  #===================
  #=== Current status
  #===================
  - alias: Irrigation UI Set Default Current Status
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_current_status
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_current_status
          value: NOTHING SCHEDULED


  #=================
  #=== Cycle 1 Name
  #=================
  - alias: Irrigation UI Set Default Cycle 1 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_cycle1_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_cycle1_name
          value: Morning Cycle

  #=================
  #=== Cycle 2 Name
  #=================
  - alias: Irrigation UI Set Default Cycle 2 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_cycle2_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_cycle2_name
          value: Afternoon Cycle

  #=================
  #=== Cycle 3 Name
  #=================
  - alias: Irrigation UI Set Default Cycle 3 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_cycle3_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_cycle3_name
          value: Manual Cycle


  #================
  #=== Zone 1 Name
  #================
  - alias: Irrigation UI Set Default Zone 1 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone1_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone1_name
          value: Zone 1

  #================
  #=== Zone 2 Name
  #================
  - alias: Irrigation UI Set Default Zone 2 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone2_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone2_name
          value: Zone 2

  #================
  #=== Zone 3 Name
  #================
  - alias: Irrigation UI Set Default Zone 3 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone3_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone3_name
          value: Zone 3

  #================
  #=== Zone 4 Name
  #================
  - alias: Irrigation UI Set Default Zone 4 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone4_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone4_name
          value: Zone 4

  #================
  #=== Zone 5 Name
  #================
  - alias: Irrigation UI Set Default Zone 5 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone5_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone5_name
          value: Zone 5

  #================
  #=== Zone 6 Name
  #================
  - alias: Irrigation UI Set Default Zone 6 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone6_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone6_name
          value: Zone 6

  #================
  #=== Zone 7 Name
  #================
  - alias: Irrigation UI Set Default Zone 7 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone7_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone7_name
          value: Zone 7

  #================
  #=== Zone 8 Name
  #================
  - alias: Irrigation UI Set Default Zone 8 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone8_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone8_name
          value: Zone 8
  
  #================
  #=== Zone 9 Name
  #================
  - alias: Irrigation UI Set Default Zone 9 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone9_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone9_name
          value: Zone 9

  #================
  #=== Zone 10 Name
  #================
  - alias: Irrigation UI Set Default Zone 10 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone10_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone10_name
          value: Zone 10

  #================
  #=== Zone 11 Name
  #================
  - alias: Irrigation UI Set Default Zone 11 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone11_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone11_name
          value: Zone 11

  #================
  #=== Zone 12 Name
  #================
  - alias: Irrigation UI Set Default Zone 12 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone12_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone12_name
          value: Zone 12

  #================
  #=== Zone 13 Name
  #================
  - alias: Irrigation UI Set Default Zone 13 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone13_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone13_name
          value: Zone 13

  #================
  #=== Zone 14 Name
  #================
  - alias: Irrigation UI Set Default Zone 14 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone14_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone14_name
          value: Zone 14

  #================
  #=== Zone 15 Name
  #================
  - alias: Irrigation UI Set Default Zone 15 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone15_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone15_name
          value: Zone 15

  #================
  #=== Zone 16 Name
  #================
  - alias: Irrigation UI Set Default Zone 16 Name
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone16_name
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone16_name
          value: Zone 16



  #============================
  #=== Zone 1 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 1 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone1_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone1_switch_entity_id
          value: switch.zone1

  #============================
  #=== Zone 2 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 2 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone2_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone2_switch_entity_id
          value: switch.zone2

  #============================
  #=== Zone 3 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 3 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone3_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone3_switch_entity_id
          value: switch.zone3

  #============================
  #=== Zone 4 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 4 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone4_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone4_switch_entity_id
          value: switch.zone4

  #============================
  #=== Zone 5 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 5 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone5_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone5_switch_entity_id
          value: switch.zone5

  #============================
  #=== Zone 6 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 6 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone6_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone6_switch_entity_id
          value: switch.zone6

  #============================
  #=== Zone 7 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 7 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone7_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone7_switch_entity_id
          value: switch.zone7

  #============================
  #=== Zone 8 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 8 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone8_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone8_switch_entity_id
          value: switch.zone8
  
  #============================
  #=== Zone 9 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 9 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone9_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone9_switch_entity_id
          value: switch.zone9

  #============================
  #=== Zone 10 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 10 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone10_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone10_switch_entity_id
          value: switch.zone10

  #============================
  #=== Zone 11 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 11 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone11_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone11_switch_entity_id
          value: switch.zone11

  #============================
  #=== Zone 12 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 12 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone12_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone12_switch_entity_id
          value: switch.zone12

  #============================
  #=== Zone 13 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 13 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone13_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone13_switch_entity_id
          value: switch.zone13

  #============================
  #=== Zone 14 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 14 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone14_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone14_switch_entity_id
          value: switch.zone14

  #============================
  #=== Zone 15 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 15 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone15_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone15_switch_entity_id
          value: switch.zone15

  #============================
  #=== Zone 16 Switch Entity ID
  #============================
  - alias: Irrigation UI Set Default Zone 16 Entity ID
    trigger:
      - platform: homeassistant
        event: start

    condition:
      - condition: state
        entity_id: input_text.irrigation_zone16_switch_entity_id
        state: 'unknown'

    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.irrigation_zone16_switch_entity_id
          value: switch.zone16


